const menuToggle=document.querySelector('.menu-toggle'),navMenu=document.querySelector('.nav-menu');
menuToggle?.addEventListener('click',()=>{const open=navMenu.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.nav-menu a').forEach(a=>a.addEventListener('click',()=>{navMenu?.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false');}));
const ADDRESS='Viana, Bairro 1 de Maio, Casa n.º 31, Luanda – Angola',EMAIL='geral@hmatiasps.ao';
const loc=document.querySelector('.topbar-inner > span:first-child');if(loc){loc.textContent='📍 '+ADDRESS;loc.classList.add('hmatias-location');}
const cl=document.querySelector('.contact-list');if(cl){const a=[...cl.querySelectorAll('span')].find(x=>x.textContent.includes('Luanda, Angola'));if(a)a.innerHTML='<span>⌖</span> '+ADDRESS;}
const footer=document.querySelector('footer .footer-grid > div:first-child');if(footer&&!footer.querySelector('.hmatias-address')){const p=document.createElement('p');p.className='hmatias-address';p.textContent=ADDRESS;footer.appendChild(p);}
const form=document.getElementById('contactForm');if(form){const tel=form.querySelector('#telefone');if(tel)tel.required=true;if(!form.querySelector('#email')){const label=document.createElement('label');label.htmlFor='email';label.innerHTML='E-mail<input id="email" type="email" name="email" autocomplete="email" placeholder="seu@email.com">';const phoneLabel=form.querySelector('label[for="telefone"]');phoneLabel?.before(label);}form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),text=`Olá HMATIAS.\n\nNome: ${d.get('nome')||''}\nEmpresa: ${d.get('empresa')||'Não indicada'}\nE-mail: ${d.get('email')||'Não indicado'}\nTelefone/WhatsApp: ${d.get('telefone')||'Não indicado'}\nServiço: ${d.get('servico')||'Não indicado'}\n\nMensagem:\n${d.get('mensagem')||''}`;window.open('https://wa.me/244948806673?text='+encodeURIComponent(text),'_blank','noopener');});}
const ld=document.querySelector('script[type="application/ld+json"]');if(ld)try{const x=JSON.parse(ld.textContent);x.address={...(x.address||{}),streetAddress:'Bairro 1 de Maio, Casa n.º 31',addressLocality:'Viana',addressRegion:'Luanda',addressCountry:'AO'};x.telephone='+244948806673';x.email=EMAIL;ld.textContent=JSON.stringify(x);}catch(e){}
document.querySelectorAll('a[href^="https://wa.me/244948806673"]').forEach(a=>{if(!a.href.includes('text='))a.href='https://wa.me/244948806673?text='+encodeURIComponent('Olá HMATIAS, gostaria de solicitar um orçamento. Podem orientar-me?');});
const topbar=document.querySelector('.topbar'),topbarInner=document.querySelector('.topbar-inner'),topLinks=document.querySelector('.top-links'),topContact=document.querySelector('.top-contact');if(topbar&&topbarInner&&topLinks){topbar.classList.add('hmatias-livebar');topbarInner.classList.add('hmatias-livebar-inner');topLinks.classList.add('hmatias-ticker');const items=['Construção & Infraestrutura','Facilities & Manutenção','HMATIAS Supply · Procurement','Fornecimento Empresarial','Projetos reais · HMATIAS','Parcerias & Soluções Empresariais'];const m=items.map(x=>`<span class="ticker-item">${x}</span><span class="ticker-sep">•</span>`).join('');topLinks.innerHTML=`<div class="hmatias-ticker-track">${m}${m}</div>`;topContact?.classList.add('hmatias-top-contact');const s=document.createElement('style');s.textContent='.hmatias-livebar{overflow:hidden}.hmatias-livebar-inner{gap:22px}.hmatias-location{flex:0 0 auto;white-space:nowrap;font-weight:800;color:#fff}.hmatias-ticker{position:relative;flex:1;min-width:0;overflow:hidden;height:38px;display:flex!important;align-items:center;white-space:nowrap}.hmatias-ticker-track{display:inline-flex;align-items:center;min-width:max-content;animation:hmatiasTicker 34s linear infinite}.ticker-item{display:inline-block;color:#e9f5ff;font-size:11px;font-weight:800}.ticker-sep{margin:0 13px;color:#57bdf0}@keyframes hmatiasTicker{from{transform:translateX(0)}to{transform:translateX(-50%)}}@media(max-width:1100px){.hmatias-top-contact{display:none}}@media(max-width:850px){.hmatias-livebar{height:34px}.hmatias-livebar-inner{height:34px}.hmatias-ticker{height:34px}.hmatias-ticker-track{animation-duration:28s}.ticker-item{font-size:10px}}';document.head.appendChild(s);}
const navLinks=[...document.querySelectorAll('.nav-menu a[href^="#"]')],sections=navLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);if(sections.length){const io=new IntersectionObserver(es=>{const v=es.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${v.target.id}`));},{rootMargin:'-28% 0px -58% 0px',threshold:[.05,.15,.3,.5]});sections.forEach(s=>io.observe(s));}
const back=document.createElement('button');back.className='hmatias-backtop';back.type='button';back.setAttribute('aria-label','Voltar ao início');back.textContent='↑';back.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.body.appendChild(back);addEventListener('scroll',()=>back.classList.toggle('show',scrollY>260),{passive:true});
if(!document.querySelector('link[data-hmatias-premium]')){const p=document.createElement('link');p.rel='stylesheet';p.href='premium.css?v=2';p.dataset.hmatiasPremium='true';document.head.appendChild(p);}
